set -g default-terminal "tmux-256color"
# Outer terminal (Windows Terminal etc.) supports 24-bit colour
set -as terminal-features ",xterm*:RGB"
set -g base-index 1
set -g pane-base-index 1

set -g prefix `
bind ` send-prefix
set -sg escape-time 1
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g history-limit 100000

is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
bind 'h' if-shell "$is_vim" "send-keys c-w h" "select-pane -L"
bind 'j' if-shell "$is_vim" "send-keys c-w j" "select-pane -D"
bind 'k' if-shell "$is_vim" "send-keys c-w k" "select-pane -U"
bind 'l' if-shell "$is_vim" "send-keys c-w l" "select-pane -R"

bind r source-file ~/.tmux.conf

################################################################################
# Theme
################################################################################

# Statusbar
set -g status-interval 2
set -g status-bg colour247
setw -g window-status-format "#[fg=colour172] •#[fg=colour8] #I:#W"
setw -g window-status-current-format "#{?window_zoomed_flag,#[fg=colour124],#[fg=colour65]} •#[fg=colour254] #W "
set -g status-position bottom
set -g status-justify centre
set -g status-left "#[bg=colour244]  #[fg=colour172]• #[fg=colour70]• #[fg=colour75]• #[fg=black] #[bg=colour247, fg=colour244]"
set -g status-right "#[bg=colour247, fg=colour244]#[bg=colour244] #[fg=colour254] %H:%M %d/%m #[fg=colour75] •#[fg=colour254] #S  "

